n=input("Dati un numar natural n= ")
n=int(n)
print(n,"metri =",n*100, "centimetri")
print(n, "kilograme =",n*1000, "miligrame")
print(n,"ani =",n*12,"luni sau" ,n*365, "zile sau",n*52,"saptamiini")