a=input("Dati valoare lui a=")
b=input("Dati valoare lui b=")
sum=int(a)+int(b)
difference=int(a)-int(b)
cit=int(a)//int(b)
rest=int(a)%int(b)
produs=int(a)*int(b)
power=int(a)**int(b)
print("a+b= " ,sum)
print("a-b= ", difference)
print("a//b= ", cit)
print("a%b= ", rest)
print("a*b= ", produs) 
print("a**b= ", power)
